FROM postgres:16-alpine

COPY docker/init-db.sh /docker-entrypoint-initdb.d/01-init-db.sh
COPY migrations/001_initial.sql /docker-entrypoint-initdb.d/02-schema.sql

RUN chmod +x /docker-entrypoint-initdb.d/01-init-db.sh
